let suggestions = [
    "Idly",
    "Dosa",
    "Bonda",
    "Upma",
    "Butter Chicken",
    "Chana Masala",
    "Vegetable Pulao",
    "Aloo Gobi",
    "Bajji",
    "Puffs",
    "Samosa",
    "Biscuits",
    "Vegetable Biryani",
    "Palak Paneer",
    "Dal Tadka",
    "Gulab Jamun",
    "Rasgulla",
    "Kheer",
    "Jalebi",
    "sugar  -  kheer" ,  "sugar  -  Gulab jamun"
];
